const PHRASES = [
{"unit":"u55","en":"stay (in a hotel)","uz":"turmoq / yashamoq (mehmonxonada)","ru":"жить, останавливаться (в отеле)","note":""},
{"unit":"u55","en":"facilities","uz":"qulayliklar","ru":"удобства","note":""},
{"unit":"u55","en":"minibar","uz":"minibar","ru":"минибар","note":""},
{"unit":"u55","en":"internet access","uz":"internetga kirish","ru":"доступ в интернет","note":""},
{"unit":"u55","en":"satellite TV","uz":"sun'iy yo'ldosh TV","ru":"спутниковое ТВ","note":""},
{"unit":"u55","en":"air conditioning","uz":"konditsioner","ru":"кондиционер","note":""},
{"unit":"u55","en":"gym","uz":"sport zali","ru":"спортзал","note":""},
{"unit":"u55","en":"room service","uz":"xona xizmati","ru":"обслуживание номеров","note":""},
{"unit":"u55","en":"staff","uz":"xodimlar","ru":"персонал","note":""},
{"unit":"u55","en":"helpful","uz":"yordam beruvchi","ru":"услужливый","note":""},
{"unit":"u55","en":"tourist","uz":"turist","ru":"турист","note":""},
{"unit":"u55","en":"guest","uz":"mehmon","ru":"гость","note":""},
{"unit":"u55","en":"delicious","uz":"mazali","ru":"вкусный","note":""},
{"unit":"u55","en":"recommend","uz":"tavsiya qilmoq","ru":"рекомендовать","note":""},
{"unit":"u55","en":"book a room","uz":"xona band qilmoq","ru":"забронировать номер","note":""},
{"unit":"u55","en":"en suite","uz":"hammomli xona","ru":"номер с ванной","note":""},
{"unit":"u55","en":"right","uz":"tushunarli, xo'p","ru":"хорошо, ясно","note":""},
{"unit":"u55","en":"included","uz":"narxga kiritilgan","ru":"включено в цену","note":""},
{"unit":"u55","en":"that's great","uz":"bu ajoyib","ru":"это отлично","note":""},
{"unit":"u55","en":"parking","uz":"avtoturargoh","ru":"парковка","note":""},
{"unit":"u55","en":"I'm afraid not","uz":"afsuski, yo'q","ru":"боюсь, что нет","note":""},
{"unit":"u55","en":"never mind","uz":"hechqisi yo'q","ru":"неважно, ничего страшного","note":""},
{"unit":"u55","en":"details","uz":"ma'lumotlar","ru":"данные, подробности","note":""},
{"unit":"u55","en":"that's a shame / what a shame","uz":"achinarli / qanday achinarli","ru":"как жаль","note":""},
{"unit":"u55","en":"passenger","uz":"yo'lovchi","ru":"пассажир","note":""},
{"unit":"u55","en":"luggage","uz":"yuk, bagaj","ru":"багаж","note":""},
{"unit":"u55","en":"suitcase","uz":"chamadon","ru":"чемодан","note":""},
{"unit":"u56","en":"bag","uz":"sumka","ru":"сумка","note":""},
{"unit":"u56","en":"trolley","uz":"aravacha","ru":"тележка","note":""},
{"unit":"u56","en":"check-in desk","uz":"ro'yxatdan o'tish stoli","ru":"стойка регистрации","note":""},
{"unit":"u56","en":"ticket","uz":"chipta","ru":"билет","note":""},
{"unit":"u56","en":"scales","uz":"tarozi","ru":"весы","note":""},
{"unit":"u56","en":"hand luggage","uz":"qo'l yuki","ru":"ручная кладь","note":""},
{"unit":"u56","en":"window seat","uz":"deraza yonidagi joy","ru":"место у окна","note":""},
{"unit":"u56","en":"aisle seat","uz":"yo'lak yonidagi joy","ru":"место у прохода","note":""},
{"unit":"u56","en":"boarding card","uz":"bortga chiqish kartasi","ru":"посадочный талон","note":""},
{"unit":"u56","en":"departed","uz":"jo'nab ketgan","ru":"вылетел","note":""},
{"unit":"u56","en":"flight closed","uz":"reys yopilgan","ru":"регистрация закрыта","note":""},
{"unit":"u56","en":"last call","uz":"oxirgi chaqiruv","ru":"последнее объявление","note":""},
{"unit":"u56","en":"gate","uz":"chiqish eshigi","ru":"выход на посадку","note":""},
{"unit":"u56","en":"boarding","uz":"bortga chiqish","ru":"посадка","note":""},
{"unit":"u56","en":"delayed","uz":"kechiktirilgan","ru":"задержан","note":""},
{"unit":"u56","en":"get on (the plane)","uz":"samolyotga chiqmoq","ru":"сесть в самолёт","note":""},
{"unit":"u56","en":"fasten your seat belt","uz":"kamarni bog'lamoq","ru":"пристегнуть ремень","note":""},
{"unit":"u56","en":"take off","uz":"parvoz qilmoq","ru":"взлетать","note":""},
{"unit":"u56","en":"land","uz":"qo'nmoq","ru":"приземляться","note":""},
{"unit":"u56","en":"get off","uz":"tushmoq (samolyotdan)","ru":"выйти из самолёта","note":""},
{"unit":"u56","en":"go through passport control","uz":"pasport nazoratidan o'tmoq","ru":"пройти паспортный контроль","note":""},
{"unit":"u56","en":"check (passport)","uz":"tekshirmoq","ru":"проверять","note":""},
{"unit":"u56","en":"collect (luggage)","uz":"yig'ib olmoq","ru":"забрать багаж","note":""},
{"unit":"u56","en":"baggage reclaim","uz":"bagaj olish joyi","ru":"выдача багажа","note":""},
{"unit":"u56","en":"go through customs","uz":"bojxonadan o'tmoq","ru":"пройти таможню","note":""},
{"unit":"u56","en":"leave","uz":"tark etmoq","ru":"покинуть","note":""},
{"unit":"u56","en":"terminal","uz":"terminal","ru":"терминал","note":""},
{"unit":"u57","en":"resort","uz":"kurort, dam olish maskani","ru":"курорт, место отдыха","note":""},
{"unit":"u57","en":"fly (flew)","uz":"uchib bormoq (samolyotda)","ru":"лететь (самолётом)","note":""},
{"unit":"u57","en":"get a bus / take a bus","uz":"avtobusda bormoq","ru":"ехать на автобусе","note":""},
{"unit":"u57","en":"rent an apartment/house","uz":"kvartira/uy ijaraga olmoq","ru":"снимать квартиру/дом","note":""},
{"unit":"u57","en":"apartment (flat)","uz":"kvartira","ru":"квартира","note":""},
{"unit":"u57","en":"beach","uz":"plyaj","ru":"пляж","note":""},
{"unit":"u57","en":"lie (lay)","uz":"yotmoq (o'tgan zamon)","ru":"лежать (прош. вр.)","note":""},
{"unit":"u57","en":"sunbathe","uz":"quyoshda toblanmoq","ru":"загорать","note":""},
{"unit":"u57","en":"swimming costume","uz":"cho'milish kiyimi (ayollar)","ru":"купальный костюм","note":""},
{"unit":"u57","en":"shorts","uz":"shortik","ru":"шорты","note":""},
{"unit":"u57","en":"sea","uz":"dengiz","ru":"море","note":""},
{"unit":"u57","en":"relax","uz":"dam olmoq, hordiq chiqarmoq","ru":"отдыхать, расслабляться","note":""},
{"unit":"u57","en":"an hour or so","uz":"taxminan bir soat","ru":"примерно час","note":""},
{"unit":"u57","en":"go for a walk","uz":"sayr qilmoq","ru":"идти гулять","note":""},
{"unit":"u57","en":"perfect","uz":"mukammal, ajoyib","ru":"идеальный, превосходный","note":""},
{"unit":"u57","en":"postcard","uz":"otkritka","ru":"открытка","note":""},
{"unit":"u58","en":"map","uz":"xarita","ru":"карта","note":""},
{"unit":"u58","en":"guide","uz":"gid, yo'lboshchi","ru":"гид","note":""},
{"unit":"u58","en":"guidebook","uz":"sayohat qo'llanmasi","ru":"путеводитель","note":""},
{"unit":"u58","en":"typical","uz":"odatiy, tipik","ru":"типичный","note":""},
{"unit":"u58","en":"go sightseeing","uz":"diqqatga sazovor joylarni ko'rmoq","ru":"осматривать достопримечательности","note":""},
{"unit":"u58","en":"art gallery","uz":"san'at galereyasi","ru":"художественная галерея","note":""},
{"unit":"u58","en":"visit","uz":"tashrif buyurmoq, bormoq","ru":"посещать","note":""},
{"unit":"u58","en":"museum","uz":"muzey","ru":"музей","note":""},
{"unit":"u58","en":"look round","uz":"atrofni aylanib ko'rmoq","ru":"осматриваться, обходить","note":""},
{"unit":"u58","en":"go on a (guided) tour","uz":"(gid bilan) sayohatga bormoq","ru":"отправиться на экскурсию (с гидом)","note":""},
{"unit":"u58","en":"get lost","uz":"adashib qolmoq","ru":"заблудиться","note":""},
{"unit":"u58","en":"take photos","uz":"surat(lar) olmoq","ru":"фотографировать","note":""},
{"unit":"u60","en":"this is","uz":"bu — (kimnidir tanishtirishda)","ru":"это — (при знакомстве)","note":"Introductions"},
{"unit":"u60","en":"Hello","uz":"Salom","ru":"Здравствуйте / Привет","note":"Introductions"},
{"unit":"u60","en":"Hi","uz":"Salom (norasmiy)","ru":"Привет (неформально)","note":"Introductions"},
{"unit":"u60","en":"Nice to meet you","uz":"Siz bilan tanishganimdan xursandman","ru":"Приятно познакомиться","note":"Introductions"},
{"unit":"u60","en":"Good to meet you","uz":"Siz bilan tanishganimdan xursandman","ru":"Рад встрече / Приятно познакомиться","note":"Introductions"},
{"unit":"u60","en":"I hope to see you again","uz":"Sizni yana ko'rishni umid qilaman","ru":"Надеюсь увидеть вас снова","note":"Introductions"},
{"unit":"u60","en":"shake hands","uz":"qo'l siqishmoq","ru":"пожимать руки","note":"Introductions"},
{"unit":"u60","en":"bye","uz":"xayr (goodbye ning qisqartmasi)","ru":"пока (сокращение от goodbye)","note":"Introductions"},
{"unit":"u60","en":"How are you?","uz":"Qalaysiz? / Ishlaringiz qanday?","ru":"Как дела?","note":"Meeting a friend"},
{"unit":"u60","en":"Fine, thanks. And you?","uz":"Yaxshi, rahmat. Sizchi?","ru":"Хорошо, спасибо. А у вас?","note":"Meeting a friend"},
{"unit":"u60","en":"not bad","uz":"yomon emas, chatoq emas","ru":"неплохо","note":"Meeting a friend"},
{"unit":"u60","en":"I've got to go now","uz":"Menga hozir ketish kerak","ru":"Мне пора идти","note":"Meeting a friend"},
{"unit":"u60","en":"See you later","uz":"Keyinroq ko'rishguncha","ru":"Увидимся позже","note":"Meeting a friend"},
{"unit":"u60","en":"See you then","uz":"O'sha vaqtda ko'rishguncha (kelishilgan vaqtda)","ru":"Тогда увидимся (в оговорённое время)","note":"Meeting a friend"},
{"unit":"u60","en":"See you soon","uz":"Tez orada ko'rishguncha","ru":"До скорой встречи","note":"Meeting a friend"},
{"unit":"u60","en":"See you again","uz":"Yana ko'rishguncha","ru":"До новой встречи","note":"Meeting a friend"},
{"unit":"u67","en":"Sorry","uz":"Kechirasiz / Uzr","ru":"","note":""},
{"unit":"u67","en":"I'm sorry, I've broken a cup.","uz":"Kechirasiz, men chinni piyolani sindirib qo'ydim.","ru":"","note":""},
{"unit":"u67","en":"I'm very sorry","uz":"Juda uzr so'rayman","ru":"","note":""},
{"unit":"u67","en":"I've lost your pen.","uz":"Ruchkangizni yo'qotib qo'ydim.","ru":"","note":""},
{"unit":"u67","en":"I forgot to post your letter.","uz":"Xatingizni jo'natishni unutib qo'ydim.","ru":"","note":""},
{"unit":"u67","en":"I'm really sorry.","uz":"Chindan ham uzr so'rayman.","ru":"","note":""},
{"unit":"u67","en":"Sorry I'm late.","uz":"Kechikkanim uchun uzr.","ru":"","note":""},
{"unit":"u67","en":"That's all right.","uz":"Hechqisi yo'q.","ru":"","note":""},
{"unit":"u67","en":"That's OK.","uz":"Mayli, hechqisi yo'q.","ru":"","note":""},
{"unit":"u67","en":"Don't worry.","uz":"Xavotir olmang.","ru":"","note":""},
{"unit":"u67","en":"It doesn't matter.","uz":"Muhim emas / Farqi yo'q.","ru":"","note":""},
{"unit":"u67","en":"Never mind.","uz":"Xafa bo'lmang / Farqi yo'q.","ru":"","note":""},
{"unit":"u67","en":"apologize to someone","uz":"kimdandir uzr so'ramoq","ru":"","note":""},
{"unit":"u67","en":"rude","uz":"qo'pol","ru":"","note":""},
{"unit":"u67","en":"polite","uz":"odobli, xushmuomala","ru":"","note":""},
{"unit":"u67","en":"that's all right / don't worry / it doesn't matter / never mind","uz":"hechqisi yo'q / xavotir olmang / muhim emas / farqi yo'q","ru":"","note":""},
{"unit":"u67","en":"break (PT broke, PP broken)","uz":"sindirmoq","ru":"","note":""},
{"unit":"u67","en":"lose (PT/PP lost)","uz":"yo'qotmoq","ru":"","note":""},
{"unit":"u67","en":"forget (PT forgot, PP forgotten)","uz":"unutmoq","ru":"","note":""},
{"unit":"u67","en":"remember","uz":"eslamoq","ru":"","note":""},
{"unit":"u67","en":"really sorry","uz":"chindan ham uzr / juda uzr","ru":"","note":""},
{"unit":"u67","en":"sorry I'm late","uz":"kechikkanim uchun uzr","ru":"","note":""},
{"unit":"u67","en":"(I'm sorry)","uz":"(Kechirasiz)","ru":"","note":""},
{"unit":"u67","en":"Sorry, could you repeat that, please?","uz":"Kechirasiz, buni qaytarib bera olasizmi?","ru":"","note":""},
{"unit":"u67","en":"no problem","uz":"muammo emas / hechqisi yo'q","ru":"","note":""},
{"unit":"u67","en":"I'm sorry, what was your name again?","uz":"Kechirasiz, ismingiz nima edi?","ru":"","note":""},
{"unit":"u68","en":"I think the school is excellent.","uz":"Menimcha, maktab a'lo darajada.","ru":"","note":""},
{"unit":"u68","en":"opinion","uz":"fikr","ru":"","note":""},
{"unit":"u68","en":"I thought it was a very funny book.","uz":"Men buni juda kulgili kitob deb o'yladim.","ru":"","note":""},
{"unit":"u68","en":"What do you think of London?","uz":"London haqida nima deb o'ylaysiz?","ru":"","note":""},
{"unit":"u68","en":"I like this dress. What do you think?","uz":"Menga bu ko'ylak yoqadi. Siz nima deb o'ylaysiz?","ru":"","note":""},
{"unit":"u68","en":"a waste of money","uz":"pulni behuda sarflash","ru":"","note":""},
{"unit":"u68","en":"Yes, I agree.","uz":"Ha, men roziman.","ru":"","note":""},
{"unit":"u68","en":"I don't think it's very good.","uz":"Menimcha, bu unchalik yaxshi emas.","ru":"","note":""},
{"unit":"u68","en":"I agree with you.","uz":"Men siz bilan roziman.","ru":"","note":""},
{"unit":"u68","en":"Personally, I don't like big cities.","uz":"Shaxsan men katta shaharlarni yoqtirmayman.","ru":"","note":""},
{"unit":"u68","en":"I'm not sure. I think I prefer the other one.","uz":"Ishonchim komil emas. Menimcha, boshqasini afzal ko'raman.","ru":"","note":""},
{"unit":"u68","en":"I disagree. I thought it was great.","uz":"Men rozi emasman. Menimcha, u ajoyib edi.","ru":"","note":""},
{"unit":"u68","en":"think (PT thought)","uz":"o'ylamoq, fikrlamoq","ru":"","note":""},
{"unit":"u68","en":"excellent","uz":"a'lo, juda yaxshi","ru":"","note":""},
{"unit":"u68","en":"agree with someone","uz":"kimdir bilan rozi bo'lmoq","ru":"","note":""},
{"unit":"u68","en":"I don't think it's very good","uz":"u unchalik yaxshi emas deb o'ylayman","ru":"","note":""},
{"unit":"u68","en":"personally","uz":"shaxsan (o'z fikrini bildirishda ishlatiladi)","ru":"","note":""},
{"unit":"u68","en":"I'm not sure","uz":"ishonchim komil emas","ru":"","note":""},
{"unit":"u68","en":"prefer","uz":"afzal ko'rmoq","ru":"","note":""},
{"unit":"u68","en":"a waste of money","uz":"pulni behuda sarflash (pul isrofi)","ru":"","note":""},
{"unit":"u69","en":"use the phone","uz":"telefondan foydalanish","ru":"","note":""},
{"unit":"u69","en":"call","uz":"qo'ng'iroq qilmoq","ru":"","note":""},
{"unit":"u69","en":"ring","uz":"qo'ng'iroq qilmoq / jiringlamoq","ru":"","note":""},
{"unit":"u69","en":"phone someone","uz":"kimgadir qo'ng'iroq qilmoq","ru":"","note":""},
{"unit":"u69","en":"text","uz":"SMS yubormoq","ru":"","note":""},
{"unit":"u69","en":"send someone a text (message)","uz":"kimgadir SMS (xabar) yubormoq","ru":"","note":""},
{"unit":"u69","en":"take a message","uz":"xabarni qabul qilib olmoq","ru":"","note":""},
{"unit":"u69","en":"leave a message","uz":"xabar qoldirmoq","ru":"","note":""},
{"unit":"u69","en":"line","uz":"liniya (telefon aloqasi)","ru":"","note":""},
{"unit":"u69","en":"engaged/busy","uz":"band (liniya band)","ru":"","note":""},
{"unit":"u69","en":"on the phone","uz":"telefonda gaplashmoqda","ru":"","note":""},
{"unit":"u69","en":"out/isn't in","uz":"tashqarida / joyida yo'q","ru":"","note":""},
{"unit":"u69","en":"wrong number","uz":"noto'g'ri raqam","ru":"","note":""},
{"unit":"u69","en":"battery's flat","uz":"batareya tugagan (o'chgan)","ru":"","note":""},
{"unit":"u69","en":"phoned/rang","uz":"qo'ng'iroq qildi","ru":"","note":""},
{"unit":"u69","en":"phone/mobile","uz":"telefon/mobil (raqami)","ru":"","note":""},
{"unit":"u69","en":"left/took (a message)","uz":"xabar qoldirdi/qabul qildi","ru":"","note":""},
{"unit":"u69","en":"isn't in/'s out","uz":"joyida yo'q/tashqarida","ru":"","note":""},
{"unit":"u69","en":"busy/engaged","uz":"band","ru":"","note":""},
{"unit":"u69","en":"texted/sent (a text)","uz":"SMS yubordi","ru":"","note":""},
{"unit":"u69","en":"double","uz":"qo'sh (masalan, qo'sh uch)","ru":"","note":""},
{"unit":"u69","en":"oh","uz":"nol (raqam nol o'rnida 'o' deb aytiladi)","ru":"","note":""},
{"unit":"u69","en":"zero","uz":"nol","ru":"","note":""},
{"unit":"u69","en":"Is that Brenda?","uz":"Bu Brendami?","ru":"","note":""},
{"unit":"u69","en":"speaking","uz":"ha, o'zim gapiryapman (bu men)","ru":"","note":""},
{"unit":"u69","en":"This is Laura","uz":"Bu Laura (men Lauraman)","ru":"","note":""},
{"unit":"u69","en":"just a moment","uz":"bir daqiqa kuting","ru":"","note":""},
{"unit":"u69","en":"can I speak to","uz":"... bilan gaplasha olamanmi","ru":"","note":""},
{"unit":"u69","en":"at the moment","uz":"hozir, hozirgi vaqtda","ru":"","note":""},
{"unit":"u69","en":"Who's calling?","uz":"Kim so'rayapti? (Siz kimsiz?)","ru":"","note":""},
{"unit":"u69","en":"ring him back","uz":"unga qayta qo'ng'iroq qilmoq","ru":"","note":""},
{"unit":"u69","en":"get someone","uz":"kimnidir chaqirib kelmoq (telefonga)","ru":"","note":""},
{"unit":"u70","en":"asleep","uz":"uxlab yotgan","ru":"","note":"Common opposites"},
{"unit":"u70","en":"awake","uz":"uyg'oq","ru":"","note":"Common opposites"},
{"unit":"u70","en":"dead","uz":"o'lik","ru":"","note":"Common opposites"},
{"unit":"u70","en":"alive","uz":"tirik","ru":"","note":"Common opposites"},
{"unit":"u70","en":"strong","uz":"kuchli","ru":"","note":"Common opposites"},
{"unit":"u70","en":"weak","uz":"kuchsiz, ojiz","ru":"","note":"Common opposites"},
{"unit":"u70","en":"rich","uz":"boy","ru":"","note":"Common opposites"},
{"unit":"u70","en":"poor","uz":"kambag'al","ru":"","note":"Common opposites"},
{"unit":"u70","en":"common","uz":"keng tarqalgan, odatiy","ru":"","note":"Common opposites"},
{"unit":"u70","en":"unusual","uz":"g'ayrioddiy, noodatiy","ru":"","note":"Common opposites"},
{"unit":"u70","en":"useful","uz":"foydali","ru":"","note":"Common opposites"},
{"unit":"u70","en":"useless","uz":"foydasiz","ru":"","note":"Common opposites"},
{"unit":"u70","en":"wide","uz":"keng","ru":"","note":"Common opposites"},
{"unit":"u70","en":"narrow","uz":"tor","ru":"","note":"Common opposites"},
{"unit":"u70","en":"noisy","uz":"shovqinli","ru":"","note":"Common opposites"},
{"unit":"u70","en":"quiet","uz":"jim, osoyishta","ru":"","note":"Common opposites"},
{"unit":"u70","en":"helpful","uz":"foydali, yordam beradigan","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"annoying","uz":"jahl chiqaradigan, asabga teguvchi","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"irritating","uz":"jahl chiqaradigan (annoying so'ziga sinonim)","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"clear","uz":"aniq, tushunarli","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"confusing","uz":"chalkash, tushunarsiz","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"impossible","uz":"imkonsiz, mumkin emas","ru":"","note":"Classroom habits"},
{"unit":"u70","en":"possible","uz":"mumkin, imkoni bor","ru":"","note":"Classroom habits"},
{"unit":"food","en":"Mushroom","uz":"Qo'ziqorin","ru":"","note":""},
{"unit":"food","en":"Olives","uz":"Zaytunlar","ru":"","note":""},
{"unit":"food","en":"Onion","uz":"Piyoz","ru":"","note":""},
{"unit":"food","en":"Order","uz":"Buyurtma bermoq","ru":"","note":""},
{"unit":"food","en":"Pasta","uz":"Makaron","ru":"","note":""},
{"unit":"food","en":"Peas","uz":"No'xat","ru":"","note":""},
{"unit":"food","en":"Pineapple","uz":"Ananas","ru":"","note":""},
{"unit":"food","en":"Potato","uz":"Kartoshka","ru":"","note":""},
{"unit":"food","en":"Prawns","uz":"Krevetkalar","ru":"","note":""},
{"unit":"food","en":"Red pepper","uz":"Qizil qalampir","ru":"","note":""},
{"unit":"food","en":"Restaurant","uz":"Restoran","ru":"","note":""},
{"unit":"food","en":"Rice","uz":"Guruch","ru":"","note":""},
{"unit":"food","en":"Rubbish bin","uz":"Axlat qutisi","ru":"","note":""},
{"unit":"food","en":"Sandwich","uz":"Sendvich","ru":"","note":""},
{"unit":"food","en":"Sausages","uz":"Kolbasalar","ru":"","note":""},
{"unit":"food","en":"Service","uz":"Xizmat","ru":"","note":""},
{"unit":"food","en":"Strawberry","uz":"Qulupnay","ru":"","note":""},
{"unit":"food","en":"Table","uz":"Stol","ru":"","note":""},
{"unit":"food","en":"Throwaway","uz":"Bir martalik / tashlab yuboriladigan","ru":"","note":""},
{"unit":"food","en":"Tomato","uz":"Pomidor","ru":"","note":""},
{"unit":"food","en":"Tray","uz":"Patnis","ru":"","note":""},
{"unit":"food","en":"Vegetable","uz":"Sabzavot","ru":"","note":""},
{"unit":"food","en":"Waiter","uz":"Ofitsiant","ru":"","note":""},
{"unit":"food","en":"write","uz":"Yozmoq","ru":"","note":""},
{"unit":"unit1","en":"Angry","uz":"Jahli chiqqan","ru":"","note":""},
{"unit":"unit1","en":"Aunt","uz":"Xola / amma","ru":"","note":""},
{"unit":"unit1","en":"Blue","uz":"Ko`k rang","ru":"","note":""},
{"unit":"unit1","en":"Brother","uz":"Aka / uka","ru":"","note":""},
{"unit":"unit1","en":"Child","uz":"Bola","ru":"","note":""},
{"unit":"unit1","en":"Children","uz":"Bolalar","ru":"","note":""},
{"unit":"unit1","en":"Clean ( the house )","uz":"( uy ) ni tozalamoq","ru":"","note":""},
{"unit":"unit1","en":"Cook","uz":"Pishirmoq","ru":"","note":""},
{"unit":"unit1","en":"Cousin","uz":"Amakivachcha / xolavachcha","ru":"","note":""},
{"unit":"unit1","en":"Creative","uz":"Ijodkor","ru":"","note":""},
{"unit":"unit1","en":"Dad / father","uz":"Dada","ru":"","note":""},
{"unit":"unit1","en":"Daughter","uz":"Qiz ( farzand )","ru":"","note":""},
{"unit":"unit1","en":"Do ( the ironing )","uz":"( kiyim ) dazmollamoq","ru":"","note":""},
{"unit":"unit1","en":"Friendly","uz":"Do`stona","ru":"","note":""},
{"unit":"unit1","en":"Glasses","uz":"Ko`zoynak","ru":"","note":""},
{"unit":"unit1","en":"Go ( to the supermarket )","uz":"( suprmarketga ) bormoq","ru":"","note":""},
{"unit":"unit1","en":"Grandad / grandfather","uz":"Bobo","ru":"","note":""},
{"unit":"unit1","en":"Grandchild","uz":"Nabira","ru":"","note":""},
{"unit":"unit1","en":"Grandchildren","uz":"nabiralar","ru":"","note":""},
{"unit":"unit1","en":"Granddaughter","uz":"Qiz nevara","ru":"","note":""},
{"unit":"unit1","en":"Grandma / grandmother","uz":"Buvi","ru":"","note":""},
{"unit":"unit1","en":"Grandparent","uz":"Bobo yoki buvi","ru":"","note":""},
{"unit":"unit1","en":"Grandson","uz":"O`g`il nabira","ru":"","note":""},
{"unit":"unit1","en":"Hard-working","uz":"Mehnatkash","ru":"","note":""},
{"unit":"unit1","en":"Honest","uz":"Halol","ru":"","note":""},
{"unit":"unit1","en":"Husband","uz":"Er","ru":"","note":""},
{"unit":"unit1","en":"Interested","uz":"Qiziqqan","ru":"","note":""},
{"unit":"unit1","en":"Keen","uz":"Juda qiziqadigan","ru":"","note":""},
{"unit":"unit1","en":"Load","uz":"Yuklamoq","ru":"","note":""},
{"unit":"unit1","en":"Long","uz":"Uzun","ru":"","note":""},
{"unit":"unit1","en":"Mother / Mum","uz":"Ona","ru":"","note":""},
{"unit":"unit1","en":"Moustache","uz":"Mo`ylov","ru":"","note":""},
{"unit":"unit1","en":"Nephew","uz":"Jiyan ( o`g`il )","ru":"","note":""},
{"unit":"unit1","en":"Niece","uz":"Jiyan ( qiz )","ru":"","note":""},
{"unit":"unit1","en":"Parent","uz":"Ota-ona","ru":"","note":""},
{"unit":"unit1","en":"patient","uz":"Sabrli","ru":"","note":""},
{"unit":"unit1","en":"Polite","uz":"Muloyim","ru":"","note":""},
{"unit":"unit1","en":"Proud","uz":"Faxrli / faxrlangan","ru":"","note":""},
{"unit":"unit1","en":"Sensible","uz":"Farosatli","ru":"","note":""},
{"unit":"unit1","en":"Set ( the table )","uz":"( dasturxon ) tuzamoq","ru":"","note":""},
{"unit":"unit1","en":"Short","uz":"Qisqa","ru":"","note":""},
{"unit":"unit1","en":"Sister","uz":"Opa yoki singil","ru":"","note":""},
{"unit":"unit1","en":"Son","uz":"O`g`il","ru":"","note":""},
{"unit":"unit1","en":"Straight","uz":"Tekis / to`g`ri","ru":"","note":""},
{"unit":"unit1","en":"Tidy ( my bedroom )","uz":"( xonani ) tartibga keltirmoq","ru":"","note":""},
{"unit":"unit1","en":"Uncle","uz":"Amaki / to`ga","ru":"","note":""},
{"unit":"unit1","en":"Wash ( the dishes )","uz":"( idish ) yuvmoq","ru":"","note":""},
{"unit":"unit1","en":"Wavy","uz":"Jingalak","ru":"","note":""},
{"unit":"unit1","en":"Wife","uz":"Xotin","ru":"","note":""},
{"unit":"unit1","en":"worried","uz":"xavotirlangan","ru":"","note":""},
{"unit":"u73","en":"lie down","uz":"yotmoq, cho'zilmoq","ru":"лечь, лежать","note":""},
{"unit":"u73","en":"fall over","uz":"yiqilib tushmoq","ru":"упасть, свалиться","note":""},
{"unit":"u73","en":"sit down","uz":"o'tirmoq","ru":"сесть, садиться","note":""},
{"unit":"u73","en":"stand up","uz":"turmoq (oyoqqa)","ru":"встать, вставать","note":""},
{"unit":"u73","en":"give something up","uz":"biror narsani tashlamoq / tark etmoq","ru":"бросить (что-то делать), отказаться от чего-либо","note":""},
{"unit":"u73","en":"get on with someone","uz":"kimdir bilan yaxshi munosabatda bo'lmoq, kelishib ketmoq","ru":"ладить с кем-либо","note":""},
{"unit":"u73","en":"take off (plane)","uz":"(samolyot haqida) uchib ketmoq, havoga ko'tarilmoq","ru":"взлетать (о самолёте)","note":""},
{"unit":"u73","en":"grow up","uz":"voyaga yetmoq, kattalashmoq","ru":"вырасти, взрослеть","note":""},
{"unit":"u73","en":"find out something","uz":"biror narsani bilib olmoq, aniqlamoq","ru":"узнать, выяснить что-либо","note":""},
{"unit":"u73","en":"go out","uz":"tashqariga chiqmoq (ko'ngilochar tadbirga)","ru":"выходить (в кино, на дискотеку и т.п.)","note":""},
{"unit":"u73","en":"go up","uz":"oshmoq, ko'tarilmoq (narx haqida)","ru":"повышаться, расти (о цене)","note":""},
{"unit":"u73","en":"carry on with something","uz":"davom ettirmoq","ru":"продолжать что-либо","note":""},
{"unit":"u73","en":"go back","uz":"qaytib bormoq","ru":"возвращаться (куда-либо)","note":""},
{"unit":"u73","en":"wake up","uz":"uyg'onmoq","ru":"просыпаться","note":""},
{"unit":"u73","en":"take off (clothes)","uz":"yechmoq (kiyim haqida)","ru":"снимать (одежду)","note":""},
{"unit":"u73","en":"turn on","uz":"yoqmoq (yorug'lik, asbob)","ru":"включать (свет, прибор)","note":""},
{"unit":"u73","en":"put on","uz":"kiymoq (poyabzal, kiyim)","ru":"надевать (одежду, обувь)","note":""},
{"unit":"rc_unit4","en":"butterflies","uz":"kapalaklar (asabiylashish hissi)","ru":"","note":""},
{"unit":"rc_unit4","en":"normal","uz":"odatiy, normal","ru":"","note":"Synonym: regular; like usual"},
{"unit":"rc_unit4","en":"produces","uz":"ishlab chiqaradi, hosil qiladi","ru":"","note":""},
{"unit":"rc_unit4","en":"respond","uz":"javob bermoq, reaksiya bildirmoq","ru":"","note":""},
{"unit":"rc_unit4","en":"shut down","uz":"to'xtatmoq, faoliyatini yopmoq","ru":"","note":"Idiom: to stop"},
{"unit":"rc_unit4","en":"play a role in","uz":"biror narsada rol o'ynamoq, sabab bo'lmoq","ru":"","note":"Idiom: to have some part in"},
{"unit":"rc_unit4","en":"get rid of","uz":"qutulmoq, tashlab yubormoq","ru":"","note":"Idiom: to throw away; to put out of use"},
{"unit":"rc_unit4","en":"activity","uz":"faoliyat, mashg'ulot","ru":"","note":"Synonym: thing to do"},
{"unit":"rc_unit4","en":"benefit","uz":"foyda keltirmoq, foyda","ru":"","note":"Synonym: help"},
{"unit":"rc_unit4","en":"relax","uz":"dam olmoq, stressdan qutulmoq","ru":"","note":"Synonym: feel less stress or pressure"},
{"unit":"rc_unit4","en":"reduce","uz":"kamaytirmoq, qisqartirmoq","ru":"","note":"Synonym: make less or lower"},
{"unit":"rc_unit1","en":"freezing","uz":"muzdek, qattiq sovuq","ru":"","note":"Synonym: like ice"},
{"unit":"rc_unit1","en":"surprisingly","uz":"hayratlanarli darajada","ru":"","note":"Synonym: but; in fact"},
{"unit":"rc_unit1","en":"unusual","uz":"g'ayrioddiy, noodatiy","ru":"","note":"Synonym: different"},
{"unit":"rc_unit1","en":"unique","uz":"o'ziga xos, yagona","ru":"","note":"Synonym: one of a kind"},
{"unit":"rc_unit1","en":"fantastic","uz":"ajoyib, a'lo","ru":"","note":"Synonym: great"},
{"unit":"rc_unit1","en":"cozy","uz":"shinam, qulay","ru":"","note":"Synonym: comfortable and warm"},
{"unit":"rc_unit1","en":"be into","uz":"qiziqmoq, yoqtirmoq","ru":"","note":"Idiom: to enjoy doing"},
{"unit":"rc_unit1","en":"check in","uz":"ro'yxatdan o'tmoq (mehmonxonada)","ru":"","note":"Idiom: to go to the hotel's front desk and get the room key"},
{"unit":"rc_unit1","en":"made (out) of","uz":"...dan yasalgan, ...dan qurilgan","ru":"","note":"Idiom: built of"},
{"unit":"rc_unit2","en":"create","uz":"yaratmoq, tayyorlamoq","ru":"","note":"Synonym: make"},
{"unit":"rc_unit2","en":"in reality","uz":"aslida, haqiqatda","ru":"","note":"Synonym: actually; really"},
{"unit":"rc_unit2","en":"according to","uz":"...ga ko'ra, ...ning aytishicha","ru":"","note":"Synonym: as said by"},
{"unit":"rc_unit2","en":"nearly","uz":"deyarli, sal kam","ru":"","note":"Synonym: almost; close to"},
{"unit":"rc_unit2","en":"introduce","uz":"taqdim etmoq, kiritmoq","ru":"","note":"Synonym: first showed or gave"},
{"unit":"rc_unit2","en":"taste","uz":"ta'mga ega bo'lmoq, tatib ko'rmoq","ru":"","note":"Synonym: have the flavor of"},
{"unit":"rc_unit2","en":"find out (about)","uz":"bilib olmoq, aniqlamoq","ru":"","note":"Idiom: to learn (of)"},
{"unit":"rc_unit2","en":"catch on","uz":"ommallashmoq, urf bo'lmoq","ru":"","note":"Idiom: to become popular"},
{"unit":"rc_unit2","en":"dig in","uz":"ishtaha bilan yeyishni boshlamoq","ru":"","note":"Idiom: to begin eating with excitement"},
{"unit":"rc_unit3","en":"danger","uz":"xavf, muammo","ru":"","note":"Synonym: big trouble"},
{"unit":"rc_unit3","en":"detect","uz":"aniqlamoq","ru":"","note":"Synonym: find"},
{"unit":"rc_unit3","en":"information","uz":"ma'lumot","ru":"","note":"Synonym: facts"},
{"unit":"rc_unit3","en":"occur","uz":"sodir bo'lmoq","ru":"","note":"Synonym: happen"},
{"unit":"rc_unit3","en":"similar","uz":"bir xil, o'xshash","ru":"","note":"Synonym: almost the same; alike"},
{"unit":"rc_unit3","en":"keep an eye out for","uz":"kuzatib bormoq, ehtiyot bo'lmoq","ru":"","note":"Idiom: to watch for trouble or danger"},
{"unit":"rc_unit3","en":"keep up with","uz":"xabardor bo'lib turish, ortda qolmaslik","ru":"","note":"Idiom: to continue getting useful information"},
{"unit":"rc_unit3","en":"make up","uz":"tuzmoq, tayyorlamoq","ru":"","note":"Idiom: to prepare something"},
{"unit":"rc_unit5","en":"antennae","uz":"mo'ylov (hasharotlarda)","ru":"","note":""},
{"unit":"rc_unit5","en":"respond to","uz":"javob qaytarmoq, reaksiya bildirmoq","ru":"","note":""},
{"unit":"rc_unit5","en":"loud","uz":"baland (ovoz)","ru":"","note":""},
{"unit":"rc_unit5","en":"still","uz":"jim, qimirlamasdan","ru":"","note":""},
{"unit":"rc_unit5","en":"position","uz":"holat, pozitsiya","ru":"","note":""},
{"unit":"rc_unit5","en":"wake up","uz":"uyg'onmoq","ru":"","note":""},
{"unit":"rc_unit5","en":"for example","uz":"masalan, misol uchun","ru":"","note":"Idiom: like; for instance; such as"},
{"unit":"rc_unit5","en":"come out of","uz":"biror holatdan chiqmoq, uyg'onmoq","ru":"","note":"Idiom: to wake up from; to become alert"},
{"unit":"rc_unit5","en":"move around","uz":"harakatlanmoq","ru":"","note":"Idiom: to move; to have motion"},
{"unit":"rc_unit5","en":"discover","uz":"kashf etmoq, aniqlamoq","ru":"","note":"Synonym: find out"},
{"unit":"rc_unit5","en":"complex","uz":"murakkab","ru":"","note":"Synonym: complicated; not simple"},
{"unit":"rc_unit5","en":"believed","uz":"ishongan, fikr qilgan","ru":"","note":"Synonym: thought something was true"},
{"unit":"rc_unit5","en":"also","uz":"shuningdek","ru":"","note":""},
{"unit":"rc_unit5","en":"research","uz":"tadqiqot","ru":"","note":"Synonym: experiments"},
{"unit":"rc_unit5","en":"sounds","uz":"tovushlar","ru":"","note":""},
{"unit":"rc_unit6","en":"diversity","uz":"turfa xillik, har xillik","ru":"","note":"Synonym: different kinds; variety"},
{"unit":"rc_unit6","en":"famous","uz":"taniqli, mashhur","ru":"","note":"Synonym: well-known"},
{"unit":"rc_unit6","en":"grateful","uz":"minnatdor","ru":"","note":"Synonym: thankful"},
{"unit":"rc_unit6","en":"prevented","uz":"to'xtatilgan, yo'li to'silgan","ru":"","note":"Synonym: stopped"},
{"unit":"rc_unit6","en":"hold the record (as/for)","uz":"rekord o'rnatmoq","ru":"","note":"Idiom: to be known as better than anyone else"},
{"unit":"rc_unit6","en":"look up to","uz":"kimgadir havas qilmoq, hurmat qilmoq","ru":"","note":"Idiom: to admire someone; to think someone is a good person"},
{"unit":"rc_unit6","en":"lend a hand","uz":"yordam bermoq","ru":"","note":"Idiom: to help someone"},
{"unit":"rc_unit6","en":"record","uz":"rekord, eng yuqori natija","ru":"","note":"Synonym: something no one else has done"},
{"unit":"rc_unit6","en":"professional","uz":"professional, kasbiy","ru":"","note":"Synonym: skilled; earning money for doing work"},
{"unit":"rc_unit7","en":"report","uz":"xabar bermoq, hisobot bermoq","ru":"","note":"Synonym: wrote; told"},
{"unit":"rc_unit7","en":"responsibility","uz":"mas'uliyat, burch","ru":"","note":"Synonym: duty; required job"},
{"unit":"rc_unit7","en":"issue","uz":"muammo, masala","ru":"","note":"Synonym: problem; concern"},
{"unit":"rc_unit7","en":"source","uz":"manba","ru":"","note":"Synonym: place to get things from"},
{"unit":"rc_unit7","en":"view","uz":"qarash, fikr","ru":"","note":"Synonym: idea; opinion"},
{"unit":"rc_unit7","en":"balanced","uz":"muvozanatli, xolis","ru":"","note":""},
{"unit":"rc_unit7","en":"set up","uz":"tashkil qilmoq, yaratmoq","ru":"","note":"Idiom: to create; to start"},
{"unit":"rc_unit7","en":"agree with","uz":"qo'shilmoq (fikrga)","ru":"","note":"Idiom: to have the same idea or opinion as someone"},
{"unit":"rc_unit7","en":"on a daily basis","uz":"har kuni, kunlik asosda","ru":"","note":"Idiom: every day"},
{"unit":"u74","en":"at + a time","uz":"aniq vaqt bilan: at six o'clock, at midday, at midnight","ru":"","note":""},
{"unit":"u74","en":"at + a mealtime","uz":"ovqat vaqti bilan: at breakfast, at lunch, at dinner","ru":"","note":""},
{"unit":"u74","en":"at the weekend","uz":"dam olish kunlarida (shanba-yakshanba)","ru":"","note":""},
{"unit":"u74","en":"at night","uz":"kechasi, tunda","ru":"","note":""},
{"unit":"u74","en":"at Christmas","uz":"Rojdestvo paytida","ru":"","note":""},
{"unit":"u74","en":"at New Year","uz":"Yangi yil paytida","ru":"","note":""},
{"unit":"u74","en":"on + a day","uz":"aniq kun bilan: on Tuesday, on Friday evening","ru":"","note":""},
{"unit":"u74","en":"on Tuesdays","uz":"har seshanba kuni (takrorlanuvchi)","ru":"","note":""},
{"unit":"u74","en":"on my birthday","uz":"tug'ilgan kunim kuni","ru":"","note":""},
{"unit":"u74","en":"on Christmas Day","uz":"Rojdestvo kunida (25-dekabr)","ru":"","note":""},
{"unit":"u74","en":"on + a date","uz":"aniq sana bilan: on September 1st, on the sixth of May","ru":"","note":""},
{"unit":"u74","en":"in the morning","uz":"ertalab","ru":"","note":""},
{"unit":"u74","en":"in the afternoon","uz":"tushdan keyin","ru":"","note":""},
{"unit":"u74","en":"in the evening","uz":"kechqurun","ru":"","note":""},
{"unit":"u74","en":"in (the) spring/summer","uz":"bahorda/yozda","ru":"","note":""},
{"unit":"u74","en":"in (the) autumn/winter","uz":"kuzda/qishda","ru":"","note":""},
{"unit":"u74","en":"in July/December","uz":"iyulda/dekabrda","ru":"","note":""},
{"unit":"u74","en":"in 1990/2050","uz":"1990-yilda / 2050-yilda","ru":"","note":""},
{"unit":"u74","en":"in the 21st century","uz":"21-asrda (2000-2099)","ru":"","note":""},
{"unit":"u75","en":"diary","uz":"kundalik daftar, rejalar kitobi","ru":"","note":""},
{"unit":"u75","en":"last week","uz":"o'tgan hafta (NOT 'the last week')","ru":"","note":""},
{"unit":"u75","en":"ago","uz":"... oldin (uch kun oldin = three days ago)","ru":"","note":""},
{"unit":"u75","en":"yesterday","uz":"kecha","ru":"","note":""},
{"unit":"u75","en":"last night","uz":"kecha kechqurun (NOT 'yesterday night' yoki 'last evening')","ru":"","note":""},
{"unit":"u75","en":"this evening","uz":"bugun kechqurun","ru":"","note":""},
{"unit":"u75","en":"tomorrow morning","uz":"ertaga ertalab","ru":"","note":""},
{"unit":"u75","en":"this weekend","uz":"shu dam olish kunlari","ru":"","note":""},
{"unit":"u75","en":"next week","uz":"kelasi hafta (NOT 'the next week')","ru":"","note":""},
{"unit":"u75","en":"next Thursday","uz":"kelasi payshanba","ru":"","note":""},
{"unit":"u75","en":"in ten days' time","uz":"o'n kun ichida / o'n kundan keyin","ru":"","note":""},
{"unit":"u75","en":"appointment","uz":"uchrashuvga yozilish (shifokor, tish shifokori va h.k.)","ru":"","note":""},
{"unit":"u75","en":"before","uz":"oldin, avval","ru":"","note":""},
{"unit":"u75","en":"after","uz":"keyin, so'ng","ru":"","note":""},
{"unit":"u75","en":"at the moment","uz":"hozir, ayni paytda (= right now)","ru":"","note":""},
{"unit":"u75","en":"in a minute","uz":"bir daqiqadan so'ng (= one or two minutes from now)","ru":"","note":""},
{"unit":"u75","en":"soon","uz":"tez orada, yaqin orada","ru":"","note":""},
{"unit":"u75","en":"later","uz":"keyinroq (kelajakda, lekin hozir emas)","ru":"","note":""},
{"unit":"u75","en":"until","uz":"... gacha (davom etish ma'nosida; NOT 'by')","ru":"","note":""},
{"unit":"u75","en":"for","uz":"... davomida (muddatni bildiradi: for two weeks)","ru":"","note":""},
{"unit":"u75","en":"since","uz":"... dan beri (boshlangan nuqtani bildiradi: since 2003)","ru":"","note":""},
{"unit":"unit5","en":"Africa","uz":"Afrika","ru":"","note":""},
{"unit":"unit5","en":"Airport","uz":"Aeroport","ru":"","note":""},
{"unit":"unit5","en":"Antarctica","uz":"Antarktida","ru":"","note":""},
{"unit":"unit5","en":"Asia","uz":"Osiyo","ru":"","note":""},
{"unit":"unit5","en":"Attractive","uz":"Jozibador","ru":"","note":""},
{"unit":"unit5","en":"Bank","uz":"Bank","ru":"","note":""},
{"unit":"unit5","en":"Behind","uz":"Orqasida","ru":"","note":""},
{"unit":"unit5","en":"Better","uz":"Yaxshiroq","ru":"","note":""},
{"unit":"unit5","en":"Between","uz":"O'rtasida","ru":"","note":""},
{"unit":"unit5","en":"Big","uz":"Katta","ru":"","note":""},
{"unit":"unit5","en":"Bigger","uz":"Kattaroq","ru":"","note":""},
{"unit":"unit5","en":"Bus","uz":"Avtobus","ru":"","note":""},
{"unit":"unit5","en":"Bus station","uz":"Avtovokzal","ru":"","note":""},
{"unit":"unit5","en":"Busy","uz":"Gavjum","ru":"","note":""},
{"unit":"unit5","en":"Car","uz":"Mashina","ru":"","note":""},
{"unit":"unit5","en":"Car park","uz":"Avtoturargoh","ru":"","note":""},
{"unit":"unit5","en":"Church","uz":"Cherkov","ru":"","note":""},
{"unit":"unit5","en":"Cinema","uz":"Kinoteatr","ru":"","note":""},
{"unit":"unit5","en":"Clean","uz":"Toza","ru":"","note":""},
{"unit":"unit5","en":"Cleaner","uz":"Tozaroq","ru":"","note":""},
{"unit":"unit5","en":"Close to","uz":"Yaqin","ru":"","note":""},
{"unit":"unit5","en":"Coach","uz":"Shaharlararo avtobus","ru":"","note":""},
{"unit":"unit5","en":"Crossroads","uz":"Chorraha","ru":"","note":""},
{"unit":"unit5","en":"Crowd","uz":"Olomon","ru":"","note":""},
{"unit":"unit5","en":"Dirty","uz":"Iflos","ru":"","note":""},
{"unit":"unit5","en":"Easier","uz":"Osonroq","ru":"","note":""},
{"unit":"unit5","en":"East","uz":"Sharq","ru":"","note":""},
{"unit":"unit5","en":"Europe","uz":"Yevropa","ru":"","note":""},
{"unit":"unit5","en":"Exciting","uz":"Qiziqarli / hayajonli","ru":"","note":""},
{"unit":"unit5","en":"Far","uz":"Uzoq","ru":"","note":""},
{"unit":"unit5","en":"Farm","uz":"Ferma","ru":"","note":""},
{"unit":"unit5","en":"Field","uz":"Dala","ru":"","note":""},
{"unit":"unit5","en":"Fire station","uz":"Yong'in o'chirish bo'limi","ru":"","note":""},
{"unit":"unit5","en":"Friendlier","uz":"Do'stonaroq","ru":"","note":""},
{"unit":"unit5","en":"Gym","uz":"Sport zali","ru":"","note":""},
{"unit":"unit5","en":"Hall","uz":"Zal","ru":"","note":""},
{"unit":"unit5","en":"Hospital","uz":"Kasalxona","ru":"","note":""},
{"unit":"unit5","en":"Hotel","uz":"Mehmonxona","ru":"","note":""},
{"unit":"unit5","en":"In","uz":"Ichida","ru":"","note":""},
{"unit":"unit5","en":"Inside","uz":"Ichkarida","ru":"","note":""},
{"unit":"unit5","en":"In front of","uz":"Oldida","ru":"","note":""},
{"unit":"unit5","en":"Lake","uz":"Ko'l","ru":"","note":""},
{"unit":"unit5","en":"Library","uz":"Kutubxona","ru":"","note":""},
{"unit":"unit5","en":"More exciting","uz":"Yanada qiziqarliroq","ru":"","note":""},
{"unit":"unit5","en":"Mosque","uz":"Masjid","ru":"","note":""},
{"unit":"unit5","en":"Motorbike","uz":"Mototsikl","ru":"","note":""},
{"unit":"unit5","en":"Museum","uz":"Muzey","ru":"","note":""},
{"unit":"unit5","en":"Near","uz":"Yaqin","ru":"","note":""},
{"unit":"unit5","en":"Next to","uz":"Yonida","ru":"","note":""},
{"unit":"unit5","en":"Noisy","uz":"Shovqinli","ru":"","note":""},
{"unit":"unit5","en":"North","uz":"Shimol","ru":"","note":""},
{"unit":"unit5","en":"North America","uz":"Shimoliy Amerika","ru":"","note":""},
{"unit":"unit5","en":"Office block","uz":"Ofis binosi","ru":"","note":""},
{"unit":"unit5","en":"Opposite","uz":"Ro'parasida","ru":"","note":""},
{"unit":"unit5","en":"Outside","uz":"Tashqarida","ru":"","note":""},
{"unit":"unit5","en":"Park","uz":"Bog' / park","ru":"","note":""},
{"unit":"unit5","en":"Plane","uz":"Samolyot","ru":"","note":""},
{"unit":"unit5","en":"Police station","uz":"Politsiya bo'limi","ru":"","note":""},
{"unit":"unit5","en":"Post office","uz":"Pochta bo'limi","ru":"","note":""},
{"unit":"unit5","en":"Quieter","uz":"Tinchroq","ru":"","note":""},
{"unit":"unit5","en":"Rainy","uz":"Yomg'irli","ru":"","note":""},
{"unit":"unit5","en":"Roundabout","uz":"Aylanma yo'l","ru":"","note":""},
{"unit":"unit5","en":"Safer","uz":"Xavfsizroq","ru":"","note":""},
{"unit":"unit5","en":"Ship","uz":"Kema","ru":"","note":""},
{"unit":"unit5","en":"Shopping centre","uz":"Savdo markazi","ru":"","note":""},
{"unit":"unit5","en":"South","uz":"Janub","ru":"","note":""},
{"unit":"unit5","en":"South America","uz":"Janubiy Amerika","ru":"","note":""},
{"unit":"unit5","en":"Square","uz":"Maydon","ru":"","note":""},
{"unit":"unit5","en":"Station","uz":"Stansiya / vokzal","ru":"","note":""},
{"unit":"unit5","en":"Street","uz":"Ko'cha","ru":"","note":""},
{"unit":"unit5","en":"Sunny","uz":"Quyoshli","ru":"","note":""},
{"unit":"unit5","en":"Swimming pool","uz":"Suzish havzasi","ru":"","note":""},
{"unit":"unit5","en":"Taxi","uz":"Taksi","ru":"","note":""},
{"unit":"unit5","en":"Town","uz":"Shahar","ru":"","note":""},
{"unit":"unit5","en":"Traffic","uz":"Yo'l harakati","ru":"","note":""},
{"unit":"unit5","en":"Traffic lights","uz":"Svetofor","ru":"","note":""},
{"unit":"unit5","en":"Train","uz":"Poyezd","ru":"","note":""},
{"unit":"unit5","en":"Ugly","uz":"Xunuk","ru":"","note":""},
{"unit":"unit5","en":"Underground","uz":"Metro","ru":"","note":""},
{"unit":"unit5","en":"Village","uz":"Qishloq","ru":"","note":""},
{"unit":"unit5","en":"Warm","uz":"Iliq","ru":"","note":""},
{"unit":"unit5","en":"West","uz":"G'arb","ru":"","note":""},
{"unit":"unit5","en":"Wood","uz":"O'rmon / yog'ochzor","ru":"","note":""},
{"unit":"unit5","en":"Zoo","uz":"Hayvonot bog'i","ru":"","note":""},
{"unit": "rc_unit9", "en": "security", "uz": "xavfsizlik; qo'riqlash (zarar/hujumdan himoya)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "trust", "uz": "ishonch; ishonmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "posed (pose as)", "uz": "...deb o'zini ko'rsatdi, ...qiyofasiga kirdi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "expert", "uz": "mutaxassis, bilimdon shaxs", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "skills", "uz": "ko'nikmalar, qobiliyatlar", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "advised", "uz": "maslahat berdi", "ru": "", "note": "advise — maslahat bermoq"},
{"unit": "rc_unit9", "en": "get around", "uz": "chetlab o'tmoq, aylanib o'tmoq (qochmoq)", "ru": "", "note": "Idiom"},
{"unit": "rc_unit9", "en": "pose as", "uz": "...deb o'zini ko'rsatmoq, ...ro'liga kirmoq", "ru": "", "note": "Idiom"},
{"unit": "rc_unit9", "en": "in the hands of", "uz": "...ning qo'lida, ...ning ixtiyorida", "ru": "", "note": "Idiom"},
{"unit": "rc_unit9", "en": "computer", "uz": "kompyuter", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "technician", "uz": "texnik, usta (mutaxassis)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "technology", "uz": "texnologiya", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "engine", "uz": "dvigatel", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "skill", "uz": "ko'nikma, mahorat", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "waste", "uz": "isrof; chiqindi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "firewall", "uz": "xavfsizlik devori (firewall)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "change", "uz": "o'zgarish; o'zgartirmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "tax office", "uz": "soliq idorasi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "flight", "uz": "parvoz, reys", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "government", "uz": "hukumat", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "firm", "uz": "firma, kompaniya", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "unfortunately", "uz": "afsuski", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "usually", "uz": "odatda", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "extremely", "uz": "nihoyatda, juda", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "successfully", "uz": "muvaffaqiyatli, muvaffaqiyat bilan", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "manager", "uz": "menejer, boshliq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "prison", "uz": "qamoqxona", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "kept up with", "uz": "hamqadam bo'lmoq, ulgurmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "pointed out", "uz": "ko'rsatib bermoq, ta'kidlab o'tmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "got around", "uz": "chetlab o'tmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "gave up", "uz": "taslim bo'lmoq, voz kechmoq", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "fooled", "uz": "aldadi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "trusted", "uz": "ishondi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "discovered", "uz": "kashf qildi, topdi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "trusting", "uz": "ishonuvchan", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "trustworthy", "uz": "ishonchli, ishonsa bo'ladigan", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "advise", "uz": "maslahat bermoq (fe'l)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "advice", "uz": "maslahat (ot)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "Hacked", "uz": "buzib kirilgan (hack qilingan)", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "Hacker", "uz": "xaker, kompyuter buzg'unchi", "ru": "", "note": ""},
{"unit": "rc_unit9", "en": "Hacking", "uz": "xakerlik, kompyuterni buzib kirish", "ru": "", "note": ""},
{"unit":"rc_unit10","en":"experience","uz":"tajriba; voqea, kechinma","ru":"","note":""},
{"unit":"rc_unit10","en":"clever","uz":"aqlli, topqir, ziyrak","ru":"","note":""},
{"unit":"rc_unit10","en":"hobby","uz":"hobbi, qiziqish, havas","ru":"","note":""},
{"unit":"rc_unit10","en":"disagree","uz":"rozi bo'lmaslik, qarshi bo'lmoq, kelisha olmaslik","ru":"","note":""},
{"unit":"rc_unit10","en":"rare","uz":"nodir, kamyob, juda kam uchraydigan","ru":"","note":""},
{"unit":"rc_unit10","en":"strange","uz":"g'alati, ajib","ru":"","note":""},
{"unit":"rc_unit10","en":"[a] pair of","uz":"bir juft, ikkita (odatda bir xil narsadan)","ru":"","note":"Idiom"},
{"unit":"rc_unit10","en":"take good care of","uz":"yaxshi qaramoq, parvarish qilmoq, ehtiyot qilmoq","ru":"","note":"Idiom"},
{"unit":"rc_unit10","en":"on the other hand","uz":"boshqa tomondan, aksincha","ru":"","note":"Idiom"},
{"unit":"rc_unit10","en":"friend","uz":"do'st","ru":"","note":""},
{"unit":"rc_unit10","en":"beetle","uz":"qo'ng'iz","ru":"","note":""},
{"unit":"rc_unit10","en":"harmful","uz":"zararli","ru":"","note":""},
{"unit":"rc_unit10","en":"ordinary","uz":"oddiy","ru":"","note":""},
{"unit":"rc_unit10","en":"large","uz":"katta, yirik","ru":"","note":""},
{"unit":"rc_unit10","en":"idea","uz":"g'oya, fikr","ru":"","note":""},
{"unit":"rc_unit10","en":"home","uz":"uy, makon","ru":"","note":""},
{"unit":"rc_unit10","en":"destructive","uz":"vayron qiluvchi, halokatli","ru":"","note":""},
{"unit":"rc_unit10","en":"professional","uz":"professional, kasbiy","ru":"","note":""},
{"unit":"rc_unit10","en":"machines","uz":"mashinalar, avtomatlar","ru":"","note":""},
{"unit":"rc_unit10","en":"the wild","uz":"yovvoyi tabiat","ru":"","note":""},
{"unit":"rc_unit10","en":"diversity","uz":"xilma-xillik","ru":"","note":""},
{"unit":"rc_unit10","en":"noise","uz":"shovqin","ru":"","note":""},
{"unit":"rc_unit10","en":"record","uz":"rekord; yozuv; yozib olmoq","ru":"","note":""},
{"unit":"rc_unit10","en":"collectable","uz":"yig'ishga arziydigan (kolleksiya buyumi)","ru":"","note":""},
{"unit":"rc_unit10","en":"collect","uz":"yig'moq, to'plamoq","ru":"","note":""},
{"unit":"rc_unit10","en":"collector","uz":"kolleksioner, yig'uvchi","ru":"","note":""},
{"unit":"rc_unit10","en":"disagreements","uz":"kelishmovchiliklar, bahslar","ru":"","note":""},
{"unit":"rc_unit10","en":"disagrees","uz":"rozi bo'lmaydi, qarshi chiqadi","ru":"","note":""},
{"unit":"rc_unit10","en":"disagreeable","uz":"yoqimsiz, noxush","ru":"","note":""},
{"unit":"rc_unit10","en":"cleverness","uz":"aqllilik, topqirlik","ru":"","note":""},
{"unit":"rc_unit10","en":"cleverly","uz":"aqllik bilan, topqirlik bilan","ru":"","note":""},

// YANGI QO'SHILGAN BO'LIMLAR (Unit 6 va Travel Collocations)
{"unit":"unit6","en":"abseil (v)","uz":"arqon bilan tik qoyadan tushmoq","ru":"","note":"Tog' sportida maxsus arqonlar yordamida tepalikdan pastga tushish harakati"},
{"unit":"unit6","en":"across (prep)","uz":"kesib o'tib, narigi tomoniga","ru":"","note":"Biror maydon, yo'l yoki daryoning bir tomonidan ikkinchi tomoniga o'tish"},
{"unit":"unit6","en":"along (prep)","uz":"bo'ylab","ru":"","note":"Yo'l, daryo yoki chiziq shaklidagi biror narsaning yo'nalishi bo'yicha ketish"},
{"unit":"unit6","en":"away from (prep)","uz":"-dan uzoqda, uzoqlashib","ru":"","note":"Biror shaxs, buyum yoki joydan masofani uzoqlashtirish yo'nalishi"},
{"unit":"unit6","en":"beach (n)","uz":"plyaj, dengiz qirg'og'i","ru":"","note":"Dengiz yoki ko'l bo'yidagi qumli yoki mayda toshli dam olish joyi"},
{"unit":"unit6","en":"bear (n)","uz":"ayiq","ru":"","note":"O'rmonlarda yashaydigan, yirik va baquvvat yirtqich hayvon"},
{"unit":"unit6","en":"bee (n)","uz":"ari, asalari","ru":"","note":"Gullardan chang yig'adigan va asal beradigan qanotli foydali hasharot"},
{"unit":"unit6","en":"butterfly (n)","uz":"kapalak","ru":"","note":"Rang-barang va chiroyli qanotlarga ega bo'lgan uchuvchi hasharot"},
{"unit":"unit6","en":"climb (v)","uz":"tirmashib chiqmoq, ko'tarilmoq","ru":"","note":"Daraxtga, qoyaga yoki zinaga qo'l va oyoqlar yordamida yuqoriga chiqish"},
{"unit":"unit6","en":"cloud (n)","uz":"bulut","ru":"","note":"Osmondagi oq yoki kulrang rangli, suv bug'laridan tashkil topgan to'plam"},
{"unit":"unit6","en":"crocodile (n)","uz":"timsoh","ru":"","note":"Daryo va ko'llarda yashaydigan, o'tkir tishli, yirik yirtqich sudralib yuruvchi"},
{"unit":"unit6","en":"cycle (v)","uz":"velosiped uchmoq","ru":"","note":"Ikki g'ildirakli velosiped transportini haydash yoki boshqarish"},
{"unit":"unit6","en":"dolphin (n)","uz":"delfin","ru":"","note":"Dengiz va okeanlarda yashaydigan, juda aqlli va odamxo'sh sutemizuvchi hayvon"},
{"unit":"unit6","en":"down (prep)","uz":"pastga, pastga qarab","ru":"","note":"Yuqoridan pastki tomonga yo'naltirilgan harakat yoki holat"},
{"unit":"unit6","en":"eagle (n)","uz":"burgut","ru":"","note":"Yuksak tog'larda yashaydigan, o'tkir ko'zli, yirik va kuchli yirtqich qush"},
{"unit":"unit6","en":"ear (n)","uz":"quloq","ru":"","note":"Inson va jonzotlarning eshitish vazifasini bajaruvchi tana a'zosi"},
{"unit":"unit6","en":"elephant (n)","uz":"fil","ru":"","note":"Quruqlikda yashaydigan eng yirik, xartomli va quloqlari katta hayvon"},
{"unit":"unit6","en":"explore (v)","uz":"tadqiq qilmoq, o'rganmoq","ru":"","note":"Yangi yoki noma'lum joylarni bilish maqsadida sayohat qilish, qidirish"},
{"unit":"unit6","en":"explorer (n)","uz":"tadqiqotchi, sayyoh","ru":"","note":"Yangi yerlar, tabiat yoki madaniyatlarni kashf etuvchi sayohatchi inson"},
{"unit":"unit6","en":"eye (n)","uz":"ko'z","ru":"","note":"Atrof-muhitni ko'rish va idrok etish uchun xizmat qiladigan tana a'zosi"},
{"unit":"unit6","en":"feed (v)","uz":"boqmoq, ovqatlantirmoq","ru":"","note":"Hayvonlarga, bolalarga yoki biror kimsaga yeyish uchun taom berish"},
{"unit":"unit6","en":"feet (n)","uz":"oyoqlar (panjalari)","ru":"","note":"Foot so'zining ko'plik shakli; inson tanasining yerga tegib turadigan qismi"},
{"unit":"unit6","en":"fisherman (n)","uz":"baliqchi","ru":"","note":"Dengiz, ko'l yoki daryolardan baliq tutish bilan shug'ullanadigan shaxs"},
{"unit":"unit6","en":"flower (n)","uz":"gul","ru":"","note":"O'simliklarning chiroyli ochiladigan, xushbo'y va rang-barang qismi"},
{"unit":"unit6","en":"foot (n)","uz":"oyoq (panjasi)","ru":"","note":"Inson tana a'zosining eng pastki, poyabzal kiyiladigan qismi (birlikda)"},
{"unit":"unit6","en":"frog (n)","uz":"baqa, qurbaqa","ru":"","note":"Suvda ham, quruqlikda ham yashaydigan, sakrab harakatlanuvchi kichik jonivor"},
{"unit":"unit6","en":"from (prep)","uz":"-dan (kelib chiqish)","ru":"","note":"Harakat yoki narsaning boshlanish nuqtasi, kelib chiqish joyini bildiradi"},
{"unit":"unit6","en":"giraffe (n)","uz":"jirafa","ru":"","note":"Dunyodagi eng baland, bo'yni juda uzun bo'lgan xolli yovvoyi jonivor"},
{"unit":"unit6","en":"gorilla (n)","uz":"gorilla","ru":"","note":"Maymunlarning eng yirik, baquvvat va odamsimon turi"},
{"unit":"unit6","en":"grass (n)","uz":"o't, maysa","ru":"","note":"Yerni qoplab turadigan, chorva mollari iste'mol qiladigan yashil o'simlik"},
{"unit":"unit6","en":"ground (n)","uz":"yer, zamin","ru":"","note":"Biz ustida yuradigan qattiq tuproq yoki maydon yuzasi"},
{"unit":"unit6","en":"hippo (n)","uz":"begemot","ru":"","note":"Suvda ko'p vaqt o'tkazadigan, tanasi juda ulkan va og'ir yovvoyi hayvon"},
{"unit":"unit6","en":"into (prep)","uz":"ichiga, ichkarisiga","ru":"","note":"Biror narsaning yoki joyning yopiq hududi ichiga yo'nalgan harakat"},
{"unit":"unit6","en":"journalist (n)","uz":"jurnalist","ru":"","note":"Gazeta, jurnal yoki TV uchun yangiliklar to'plovchi va maqola yozuvchi xodim"},
{"unit":"unit6","en":"kangaroo (n)","uz":"kenguru","ru":"","note":"Avstraliyada yashaydigan, qornida xaltasi bor va sakrab yuradigan hayvon"},
{"unit":"unit6","en":"kayak (n)","uz":"kayak qayig'i","ru":"","note":"Bir yoki ikki kishilik, ikki tomonlama eshkakka ega bo'lgan sport qayig'i"},
{"unit":"unit6","en":"keep (v)","uz":"saqlamoq, asramoq","ru":"","note":"Biror narsani yo'qotmasdan o'zida saqlash yoki hayvonlarni parvarishlash"},
{"unit":"unit6","en":"last (month) (det)","uz":"o'tgan (oy)","ru":"","note":"Hozirigidan aynan bitta oldingi kelgan vaqt oralig'i (masalan, o'tgan oy)"},
{"unit":"unit6","en":"leg (n)","uz":"oyoq (boldir-son)","ru":"","note":"Inson yoki hayvon tana a'zosi; yurish va turish uchun xizmat qiladi"},
{"unit":"unit6","en":"lion (n)","uz":"sher, arslon","ru":"","note":"Hayvonlar podshosi deb ataladigan, yirik va yoldor yirtqich mushuksimon"},
{"unit":"unit6","en":"look (v)","uz":"qaramoq, ko'rinmoq","ru":"","note":"Ko'zni biror narsaga qaratish yoki tashqi ko'rinishdan ma'lum holatda bo'lish"},
{"unit":"unit6","en":"monkey (n)","uz":"maymun","ru":"","note":"Daraxtlarda chaqqon chiquvchi, dumi uzun va odamga taqlid qiluvchi jonivor"},
{"unit":"unit6","en":"moon (n)","uz":"oy","ru":"","note":"Tunda osmonda porlab turadigan Yerning yagona tabiiy yo'ldoshi"},
{"unit":"unit6","en":"mouth (n)","uz":"og'iz","ru":"","note":"Gapirish va ovqatlanish uchun xizmat qiladigan yuz qismidagi a'zo"},
{"unit":"unit6","en":"off (adv)","uz":"-dan uzoqlashib, o'chiq","ru":"","note":"Biror yuza yoki joyni tark etish harakati, yoki asbobning o'chgan holati"},
{"unit":"unit6","en":"onto (prep)","uz":"ustiga","ru":"","note":"Harakat orqali biror narsaning ustki yuzasiga chiqish yoki qo'nish"},
{"unit":"unit6","en":"over (adv)","uz":"tepasidan, oshib","ru":"","note":"Biror narsaga tegmasdan, uning yuqori qismidan o'tib ketish harakati"},
{"unit":"unit6","en":"past (adj)","uz":"o'tgan, o'tib ketgan","ru":"","note":"Vaqt nuqtai nazaridan ortda qolgan kunlar yoki biror binoning yonidan o'tish"},
{"unit":"unit6","en":"paw (n)","uz":"panja","ru":"","note":"It, mushuk, ayiq kabi hayvonlarning tirnoqli, yumshoq oyoq panjasi"},
{"unit":"unit6","en":"pilot (n)","uz":"uchuvchi, pilot","ru":"","note":"Samolyot, vertolyot yoki kosmik kemani boshqaradigan mutaxassis shaxs"},

{"unit":"nav5e","en":"buy a ticket","uz":"chipta (bilet) sotib olmoq","ru":"","note":""},
{"unit":"nav5e","en":"get to / travel to school","uz":"maktabga yetib bormoq / bormoq","ru":"","note":""},
{"unit":"nav5e","en":"get to / travel to work","uz":"ishga yetib bormoq / bormoq","ru":"","note":""},
{"unit":"nav5e","en":"get to / travel to London","uz":"Londonga yetib bormoq / bormoq","ru":"","note":""},
{"unit":"nav5e","en":"get to / travel to the shops","uz":"do'konlarga yetib bormoq / bormoq","ru":"","note":""},
{"unit":"nav5e","en":"get on / off a bus","uz":"avtobusga minmoq / avtobusdan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"get on / off a train","uz":"poyezdga minmoq / poyezddan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"get on / off a tram","uz":"tramvayga minmoq / tramvaydan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"get in / out of a car","uz":"mashinaga o'tirmoq / mashinadan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"get in / out of a taxi","uz":"taksiga o'tirmoq / taksidan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"get in / out of a van","uz":"furgonga o'tirmoq / furgondan tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"go up / down the stairs","uz":"zinadan tepaga ko'tarilmoq / pastga tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"go up / down the escalator","uz":"eskalatordan tepaga ko'tarilmoq / pastga tushmoq","ru":"","note":""},
{"unit":"nav5e","en":"go by taxi","uz":"taksi bilan (taksida) bormoq","ru":"","note":""},
{"unit":"nav5e","en":"go by bus","uz":"avtobus bilan (avtobusda) bormoq","ru":"","note":""},
{"unit":"nav5e","en":"go by tram","uz":"tramvay bilan (tramvayda) bormoq","ru":"","note":""},
{"unit":"nav5e","en":"go by train","uz":"poyezd bilan (poyezdda) bormoq","ru":"","note":""},
{"unit":"nav5e","en":"go by plane","uz":"samolyot bilan (samolyotda) bormoq","ru":"","note":""},
{"unit":"nav5e","en":"take a taxi","uz":"taksi tutmoq / taksiga o'tirmoq","ru":"","note":""},
{"unit":"nav5e","en":"take a bus","uz":"avtobusga o'tirmoq / avtobusdan foydalanmoq","ru":"","note":""},
{"unit":"nav5e","en":"take a tram","uz":"tramvayga o'tirmoq","ru":"","note":""},
{"unit":"nav5e","en":"take a train","uz":"poyezdga o'tirmoq / poyezdda yurmoq","ru":"","note":""},
{"unit":"nav5e","en":"take a plane","uz":"samolyotga o'tirmoq / samolyot uchmoq","ru":"","note":""},
{"unit":"nav5e","en":"catch a bus","uz":"avtobusga ulgurmoq (tutib qolmoq)","ru":"","note":""},
{"unit":"nav5e","en":"catch a tram","uz":"tramvayga ulgurmoq","ru":"","note":""},
{"unit":"nav5e","en":"catch a train","uz":"poyezdga ulgurmoq","ru":"","note":""},
{"unit":"nav5e","en":"catch a plane","uz":"samolyotga ulgurmoq","ru":"","note":""},
{"unit":"nav5e","en":"miss a train","uz":"poyezdni o'tkazib yubormoq (kechikmoq)","ru":"","note":""},
{"unit":"nav5e","en":"miss a bus","uz":"avtobusni o'tkazib yubormoq (kechikmoq)","ru":"","note":""},
{"unit":"nav5e","en":"miss a tram","uz":"tramvayni o'tkazib yubormoq (kechikmoq)","ru":"","note":""},
{"unit":"nav5e","en":"miss a plane","uz":"samolyotga kechikmoq","ru":"","note":""},
{"unit":"nav5e","en":"go on foot","uz":"piyoda bormoq","ru":"","note":""},
{"unit":"nav5e","en":"ride a bicycle","uz":"velosiped uchmoq","ru":"","note":""},
{"unit":"nav5e","en":"ride a motorbike","uz":"mototsikl uchmoq","ru":"","note":""},
{"unit":"nav5e","en":"ride a scooter","uz":"skuter uchmoq","ru":"","note":""},
{"unit":"nav5e","en":"ride a horse","uz":"ot minmoq","ru":"","note":""},
{"unit":"nav5e","en":"lose your way","uz":"yo'ldan adashmoq","ru":"","note":""},
{"unit":"nav5e","en":"cross the road","uz":"yo'lni (ko'chani) kesib o'tmoq","ru":"","note":""},
{"unit":"nav5e","en":"drive to work","uz":"ishga mashinada bormoq","ru":"","note":""},
{"unit":"nav5e","en":"drive into town","uz":"shaharga mashinada bormoq","ru":"","note":""},
{"unit":"nav5e","en":"drive to London","uz":"Londonga mashinada bormoq","ru":"","note":""},
{"unit":"nav5e","en":"wait for a bus","uz":"avtobus kutmoq","ru":"","note":""},
{"unit":"nav5e","en":"wait for a tram","uz":"tramvay kutmoq","ru":"","note":""},
{"unit":"nav5e","en":"wait for a train","uz":"poyezd kutmoq","ru":"","note":""},
{"unit":"nav5e","en":"give somebody a lift","uz":"kimdirni mashinada tashlab qo'ymoq (eltib qo'ymoq)","ru":"","note":""}
];

const CATEGORIES = [
  {key:"rc_unit10", name:"10-Unit: Bugs for Sale", em:"📖", type:"rc"},
  {key:"rc_unit9", name:"9-Unit: Don’t Trust Me!", em:"📖", type:"rc"},
  {key:"rc_unit7", name:"7-Unit: Not the Normal News", em:"📖", type:"rc"},
  {key:"rc_unit6", name:"6-Unit: Tiger's Tale", em:"📖", type:"rc"},
  {key:"rc_unit5", name:"5-Unit: A Bug's Sleep", em:"📖", type:"rc"},
  {key:"rc_unit4", name:"4-Unit: Butterflies in the Stomach", em:"📖", type:"rc"},
  {key:"rc_unit3", name:"3-Unit: Hurricane Who?", em:"📖", type:"rc"},
  {key:"rc_unit2", name:"2-Unit: Food Firsts", em:"📖", type:"rc"},
  {key:"rc_unit1", name:"1-Unit: The Ice Hotel", em:"📖", type:"rc"},
  {key:"u75", name:"75-Unit: Time words and phrases", em:"⏳", type:"ef"},
  {key:"u74", name:"74-Unit: Prepositions of time", em:"🕒", type:"ef"},
  {key:"u73", name:"73-Unit: Phrasal Verbs", em:"🏃‍♂️", type:"ef"},
  {key:"u70", name:"70-Unit: Sifatlar (Adjectives)", em:"🔤", type:"ef"},
  {key:"u69", name:"69-Unit: Telefon orqali gaplashish", em:"☎️", type:"ef"},
  {key:"u68", name:"68-Unit: Fikr bildirish", em:"💭", type:"ef"},
  {key:"u67", name:"67-Unit: Kechirim so'rash", em:"🙏", type:"ef"},
  {key:"u60", name:"60-Unit: Tanishish va salomlashish", em:"🤝", type:"ef"},
  {key:"u58", name:"58-Unit: Sayohat va diqqatga sazovorlik", em:"🗺️", type:"ef"},
  {key:"u57", name:"57-Unit: Plyajda dam olish", em:"🏖", type:"ef"},
  {key:"u56", name:"56-Unit: Aeroport (Airport)", em:"✈️", type:"ef"},
  {key:"u55", name:"55-Unit: Mehmonxona (Hotel)", em:"🏨", type:"ef"},
  {key:"unit6", name:"Unit 6: Wordlist (Yangi Format)", em:"🗺️", type:"ef"},
  {key:"unit5", name:"Unit 5: Elementary", em:"🗺️", type:"ef"},
  {key:"unit1", name:"Unit 1: Oila va Sifatlar (Wordlist 1)", em:"👨‍👩‍👧‍👦", type:"ef"},
  {key:"nav5e", name:"Navigate A2: Travel Collocations", em:"✈️", type:"ef"},
  {key:"food", name:"Oziq-ovqat va restoran lug'ati", em:"🍽", type:"ef"}
];